main:
	gcc -c 6-process_semaphore.c -o 6-process_semaphore.o
	gcc 6-process_semaphore.o -o 6-process_semaphore.out -lpthread
	@echo "==============OK================="
clean:
	rm -rf 	6-process_semaphore.o
	rm -rf 6-process_semaphore.out
	@echo "++++++OK++++++++"
